#Parameters used for creating and processing dataset
raw_path: data\\01_raw\\data_256
processed_path: data\\05_model_input\\data_256
prune_frac: 0.70
delete_raw_data: True
batch_size: 4
dataloader_num_workers: 0